
grafana:
  service:
    # Change this to LoadBalancer to make it accesible and uncomment outputs to get ip
    type: "ClusterIP"

prometheus:
  service:
    # Change this to LoadBalancer to make it accesible and uncomment outputs to get ip
    type: "ClusterIP"
  additionalServiceMonitors:
    - name: "ltc-api-monitor"
      selector:
        matchLabels:
          app: "ltcapi"
      namespaceSelector:
        matchNames:
          - default
      endpoints:
      - port: "ltcapi"
        path: "/metrics"
        interval: "15s"