name: CI/CD Docker Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: ltcDevOps

jobs:
  build:
    name: build and deplot to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/chekout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker front end image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ltcDevOps/frontend:latest
          
      - name: Build and push Docker api image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ltcDevOps/api:latest
      

